### ISSUE TITLE
Sequence headers and information about genes

### ISSUE THREAD

**Issue by cmayer** [tomasbruna/orthodb-clades#2]
I found the 
Vertebrata.fa.gz file on
https://bioinf.uni-greifswald.de/bioinf/partitioned_odb11/

which was created with this software.

I wonder what the sequence headers, e.g.

\>10020_0:000002	10020_0

tells me.

Indeed I would like to know what gene this is. Is there a way I can trace this gene back to the genes in OrthoDB?

Many thanks in advance!

**Comment by tomasbruna** [comment]
Hi @cmayer,

The headers come directly from OrthoDB (not modified by this software). You can trace them using the file at  [odb11v0_genes.tab.gz](https://data.orthodb.org/download/odb11v0_genes.tab.gz). For example, the header you mentioned can be traced to:

    10020_0:000002	10020_0	XP_012867311.1	Epha4	A0A1S3ESC9		105982283	Receptor protein-tyrosine kinas

If you are interested only in the species names (the first part of the ID before the colon), that's available at [odb11v0_species.tab.gz](https://data.orthodb.org/download/odb11v0_species.tab.gz).

Tomas

**Comment by cmayer** [comment]
Hi Tomas,

many thanks!

Christoph
